# Generated by Django 4.2.3 on 2023-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
