# Generated by Django 4.2.3 on 2023-10-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('exam_name', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=9)),
                ('question_file', models.FileField(upload_to='questions/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.university')),
            ],
        ),
    ]
