# Generated by Django 4.2.3 on 2023-10-26 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_question_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_name',
            field=models.CharField(choices=[('1st_mid', '1st Mid Term'), ('2nd_mid', '2nd Mid Term'), ('3rd_mid', '3rd Mid Term'), ('class_test', 'Class Test'), ('lab_test', 'Lab Test'), ('lab_final', 'Lab Final'), ('sem_year_final', 'Semester/Year Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
