# Generated by Django 4.2.3 on 2023-10-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_question_upload_time_alter_question_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.university'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
