# Generated by Django 4.2.3 on 2023-10-26 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0007_alter_question_exam_name_alter_question_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uploaded_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
