# Generated by Django 4.2.3 on 2023-10-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_question_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='uploaded_by',
        ),
    ]
