# Generated by Django 4.2.3 on 2023-10-29 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.FileField(default=None, upload_to='task/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskPhoto',
        ),
    ]
